#!/usr/bin/env python3
"""Run git-petri straight from a checkout (symlink this file into your PATH)."""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))

from gitpetri.cli import main

sys.exit(main())
